server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudgateway?
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      generate-ddl: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.apllication.instance_id}:${random_value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.catalogservice: DEBUG